# Generated by Django 2.0.5 on 2018-07-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180715_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
