# Generated by Django 2.0.5 on 2018-07-15 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180715_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_from', models.TimeField()),
                ('monday_to', models.TimeField()),
                ('tuesday_from', models.TimeField()),
                ('tuesday_to', models.TimeField()),
                ('wednesday_from', models.TimeField()),
                ('wednesday_to', models.TimeField()),
                ('thursday_from', models.TimeField()),
                ('thursday_to', models.TimeField()),
                ('friday_from', models.TimeField()),
                ('friday_to', models.TimeField()),
                ('saturday_from', models.TimeField()),
                ('saturday_to', models.TimeField()),
                ('sunday_from', models.TimeField()),
                ('sunday_to', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Restaurant')),
            ],
        ),
    ]
