# Generated by Django 2.0.5 on 2018-07-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.Restaurant'),
        ),
    ]
