# Generated by Django 2.0.5 on 2018-07-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20180715_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='restaurant',
        ),
    ]
