# Generated by Django 2.0.5 on 2018-07-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_remove_openinghours_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.OpeningHours'),
            preserve_default=False,
        ),
    ]
