# Generated by Django 2.0.5 on 2018-07-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_restaurant_opening_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
    ]
