# Generated by Django 2.0.5 on 2018-07-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_restaurant_opening_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='restaurant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.Restaurant'),
            preserve_default=False,
        ),
    ]
