# Generated by Django 2.0.5 on 2018-07-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_restaurantphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
