# Generated by Django 2.0.5 on 2018-07-15 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_auto_20180715_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_profile_pic',
            field=models.ImageField(blank=True, upload_to='dish_profile_pics'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_profile_pic',
            field=models.ImageField(blank=True, upload_to='restaurant_profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
