# Generated by Django 2.0.5 on 2018-07-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_auto_20180715_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='major',
            new_name='course',
        ),
    ]
